### ISSUE TITLE
Keyboard Layout

### ISSUE THREAD

**Issue by BtPht** [Lut1n/ImpGears#1]
The static keys binding makes it hard to use on a non AZERTY keyboard.

**Comment by Lut1n** [comment]
yop !
dynamic keys binding is now available ;)

In a text file, a binding is made in this forme : \<function-name\>=\<key code\>
See [camera-key-binding.conf](https://github.com/Lut1n/ImpGears/blob/master/examples/voxels/camera-key-binding.conf) for an example of configuration file.

Available key codes are listed in [key-values](https://github.com/Lut1n/ImpGears/blob/master/examples/voxels/key-values).
